language_mapping = {
    "ca": "ca_core_news_trf",
    "hr": "hr_core_news_lg",
    "da": "da_core_news_trf",
    "nl": "nl_core_news_lg",
    "en": "en_core_web_trf",
    "fi": "fi_core_news_lg",
    "fr": "fr_core_news_lg",
    "de": "de_core_news_lg",
    "el": "el_core_news_lg",
    "it": "it_core_news_lg",
    "lt": "lt_core_news_lg",
    "mk": "mk_core_news_lg",
    "xx": "xx_ent_wiki_sm",
    "nb": "nb_core_news_lg",
    "pl": "pl_core_news_lg",
    "pt": "pt_core_news_lg",
    "ro": "ro_core_news_lg",
    "ru": "ru_core_news_lg",
    "es": "es_dep_news_trf",
    "sv": "sv_core_news_lg",
    "uk": "uk_core_news_trf",
}